<!-- 
	jGrouseDoc template file. Renders search pane
	@Copyright (c) 2007 by Denis Riabtchik. All rights reserved. See license.txt and http://jgrouse.com for details@
	$Id: jgsearch.xslt 276 2007-12-09 00:50:40Z denis.riabtchik $
-->

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0">
	<xsl:param name='rootPath' />
	<xsl:param name="projectDesc"/>
	<xsl:param name='version'/>
    <xsl:param name='aux_css'>not_specified</xsl:param>
	
	<xsl:output method='HTML' doctype-public="-//W3C//DTD HTML 4.01//EN"
		doctype-system="http://www.w3.org/TR/html4/strict.dtd">

	</xsl:output>
	<xsl:import href="../../common/xslt/common.xslt"/>
	
	<xsl:template match="/">
		<xsl:comment>Generated by jGrouseDoc</xsl:comment>
	
		<html>
		    <head>
                <xsl:call-template name="writeCss">
                     <xsl:with-param name="rootPath"><xsl:value-of select="$rootPath"/></xsl:with-param>
                     <xsl:with-param name="aux_css"><xsl:value-of select="$aux_css"/></xsl:with-param>
                 </xsl:call-template>
            <script type="text/javascript" src="jgdoc.js">
            </script>
			</head>
			<body>
			    <div class="search">
			    <h1>Search</h1>
				<input id="jgsSearchString" type="text" class="jgdSearchString"/>
				<div  class="jgdSearchRect" >
				    <div id="jgsSearchResults">
				        Loading....
				    </div>
				</div>
				<div id="jgsInfo" class="jgsInfo" ></div>
				</div>
			</body>
            <script type="text/javascript">
            jgdoc.Searcher.start();
            </script>
			<script type="text/javascript" src="jsindex.js">
            </script>
		</html>
	</xsl:template>
</xsl:stylesheet>
