<?php

/**
 * @author Daniel Sampedro Bello <darthdaniel85@gmail.com>
 * @link http://www.pradosoft.com/
 * @copyright Copyright &copy; 2005-2014 PradoSoft
 * @license http://www.pradosoft.com/license/
 * @version $Id$
 * @since 3.3
 * @package Wsat
 */
Prado::using("System.Wsat.TWsatBaseGenerator");

class TWsatScaffoldingGenerator extends TWsatBaseGenerator
{

        function __construct()
        {
                parent::__construct();
        }

        public function generate()
        {
                $unitName = "Example";
                $class = $this->generateClass($unitName);
                $outputClass = $this->_opFile . DIRECTORY_SEPARATOR . $unitName . ".php";
                file_put_contents($outputClass, $class);

                $outputPage = $this->_opFile . DIRECTORY_SEPARATOR . $unitName . ".page";
                $page = $this->generatePage($unitName);
                file_put_contents($outputPage, $page);
        }

        // <editor-fold defaultstate="collapsed" desc="Generate Sigle Page">
        private function generatePage($fileName, $tContentId = "Content")
        {
                return <<<EOD
<com:TContent ID="Content">   

</com:TContent>
EOD;
        }

        private function generateClass($classname)
        {
                $date = date('Y-m-d h:i:s');
                $env_user = getenv("username");
                return <<<EOD
<?php
/**
 * Auto generated by PRADO - WSAT on $date.
 * @author $env_user
 */
class $classname extends TPage
{

}
EOD;
        }

// </editor-fold>
}

?>
