/* Firebird test database schema for prado unit tests
   Requires Firebird 3.0+ (for BOOLEAN and GENERATED ... AS IDENTITY).

   Create the database file and run this script via isql:
     isql-fb -user SYSDBA -password masterkey
     SQL> CREATE DATABASE '/var/lib/firebird/data/prado_unitest.fdb'
              USER 'SYSDBA' PASSWORD 'masterkey';
     SQL> CONNECT '/var/lib/firebird/data/prado_unitest.fdb'
              USER 'SYSDBA' PASSWORD 'masterkey';
     SQL> INPUT 'tests/initdb_firebird.sql';

   Or via a single command:
     isql-fb /var/lib/firebird/data/prado_unitest.fdb -user SYSDBA \
       -password masterkey -input tests/initdb_firebird.sql
*/

CREATE TABLE table1 (
	id               INTEGER         GENERATED BY DEFAULT AS IDENTITY,
	name             VARCHAR(45)     NOT NULL,
	field1_smallint  SMALLINT        NOT NULL DEFAULT 0,
	field2_varchar   VARCHAR(255),
	field3_date      DATE,
	field4_float     FLOAT           NOT NULL DEFAULT 10,
	field5_double    DOUBLE PRECISION NOT NULL DEFAULT 0,
	field6_timestamp TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
	field7_time      TIME            NOT NULL DEFAULT '00:00:00',
	field8_bigint    BIGINT          NOT NULL DEFAULT 0,
	field9_char      CHAR(10),
	field10_boolean  BOOLEAN         NOT NULL DEFAULT FALSE,
	field11_blob     BLOB SUB_TYPE TEXT,
	CONSTRAINT pk_table1 PRIMARY KEY (id)
);

CREATE TABLE address (
	username     VARCHAR(128)     NOT NULL,
	phone        VARCHAR(40)      NOT NULL DEFAULT '',
	field1_bool  BOOLEAN          NOT NULL DEFAULT FALSE,
	field2_date  DATE             NOT NULL,
	field3_dbl   DOUBLE PRECISION NOT NULL DEFAULT 0,
	field4_int   INTEGER          DEFAULT 0 NOT NULL,
	field5_text  BLOB SUB_TYPE TEXT,
	field6_time  TIME             NOT NULL DEFAULT '00:00:00',
	field7_ts    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	field8_dec   DECIMAL(19,4)    NOT NULL DEFAULT 0,
	field9_num   NUMERIC(10,4)    NOT NULL DEFAULT 0,
	int_fk1      INTEGER          NOT NULL DEFAULT 0,
	int_fk2      INTEGER          NOT NULL DEFAULT 0,
	CONSTRAINT pk_address PRIMARY KEY (username)
);

INSERT INTO table1 (name) VALUES ('test');
INSERT INTO address (username, phone, field2_date) VALUES ('wei', '1111111', CURRENT_DATE);

COMMIT;
