-- Oracle test database schema for prado unit tests
-- Requires Oracle 12c+ (for GENERATED ... AS IDENTITY).
--
-- Setup as DBA (e.g. sqlplus sys/password@localhost/XEPDB1 as sysdba):
--   CREATE USER prado_unitest IDENTIFIED BY prado_unitest;
--   GRANT CONNECT, RESOURCE, CREATE SESSION TO prado_unitest;
--   GRANT UNLIMITED TABLESPACE TO prado_unitest;
--
-- Run as prado_unitest:
--   sqlplus prado_unitest/prado_unitest@localhost/XEPDB1 @tests/initdb_oracle.sql

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE address';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE table1';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE table1 (
	id                NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name              VARCHAR2(45)  NOT NULL,
	field1_number     NUMBER(5)     NOT NULL,
	field2_varchar2   VARCHAR2(255),
	field3_date       DATE,
	field4_float      FLOAT(53)     NOT NULL,
	field5_number_ps  NUMBER(10,4)  NOT NULL,
	field6_char       CHAR(10),
	field7_clob       CLOB,
	field8_timestamp  TIMESTAMP(6)  NOT NULL,
	field9_number2    NUMBER(8,2)   NOT NULL
);

CREATE TABLE address (
	username  VARCHAR2(128) NOT NULL,
	phone     VARCHAR2(40)  NOT NULL,
	field4_int NUMBER(10)   NOT NULL,
	int_fk1   NUMBER(10),
	int_fk2   NUMBER(10),
	CONSTRAINT pk_address PRIMARY KEY (username)
);

INSERT INTO table1 (name, field1_number, field4_float, field5_number_ps, field8_timestamp, field9_number2)
	VALUES ('test', 1, 1.0, 1.0, SYSTIMESTAMP, 1.0);
INSERT INTO address (username, phone, field4_int) VALUES ('wei', '1111111', 0);
COMMIT;
