/* Firebird test database schema for prado unit tests
   Requires Firebird 4.0+ (for GENERATED ... AS IDENTITY).

   Create the database file and run this script via isql:
     isql-fb -user SYSDBA -password masterkey
     SQL> CREATE DATABASE '/var/lib/firebird/data/prado_unitest.fdb'
              USER 'SYSDBA' PASSWORD 'masterkey';
     SQL> CONNECT '/var/lib/firebird/data/prado_unitest.fdb'
              USER 'SYSDBA' PASSWORD 'masterkey';
     SQL> INPUT 'tests/initdb_firebird.sql';

   Or via a single command:
     isql-fb /var/lib/firebird/data/prado_unitest.fdb -user SYSDBA \
       -password masterkey -input tests/initdb_firebird.sql

   NOTE: In Firebird, DEFAULT must come BEFORE NOT NULL in column definitions.
*/

CREATE TABLE table1 (
	id               INTEGER          GENERATED BY DEFAULT AS IDENTITY,
	name             VARCHAR(45)      NOT NULL,
	field1_smallint  SMALLINT         DEFAULT 0 NOT NULL,
	field2_varchar   VARCHAR(255),
	field3_date      DATE,
	field4_float     FLOAT            DEFAULT 10 NOT NULL,
	field5_double    DOUBLE PRECISION DEFAULT 0 NOT NULL,
	field6_timestamp TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
	field7_time      TIME             DEFAULT '00:00:00' NOT NULL,
	field8_bigint    BIGINT           DEFAULT 0 NOT NULL,
	field9_char      CHAR(10),
	field10_boolean  BOOLEAN          DEFAULT FALSE NOT NULL,
	field11_blob     BLOB SUB_TYPE TEXT,
	CONSTRAINT pk_table1 PRIMARY KEY (id)
);

CREATE TABLE address (
	username     VARCHAR(128)     NOT NULL,
	phone        VARCHAR(40)      DEFAULT '' NOT NULL,
	field1_bool  BOOLEAN          DEFAULT FALSE NOT NULL,
	field2_date  DATE             NOT NULL,
	field3_dbl   DOUBLE PRECISION DEFAULT 0 NOT NULL,
	field4_int   INTEGER          DEFAULT 0 NOT NULL,
	field5_text  BLOB SUB_TYPE TEXT,
	field6_time  TIME             DEFAULT '00:00:00' NOT NULL,
	field7_ts    TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
	field8_dec   DECIMAL(19,4)    DEFAULT 0 NOT NULL,
	field9_num   NUMERIC(10,4)    DEFAULT 0 NOT NULL,
	int_fk1      INTEGER          DEFAULT 0 NOT NULL,
	int_fk2      INTEGER          DEFAULT 0 NOT NULL,
	CONSTRAINT pk_address PRIMARY KEY (username)
);

INSERT INTO table1 (name) VALUES ('test');
INSERT INTO address (username, phone, field2_date) VALUES ('wei', '1111111', CURRENT_DATE);

/* Firebird upsert uses MERGE ... USING (SELECT ... FROM RDB$DATABASE) ON the PK.
   DEFAULT must come BEFORE NOT NULL in Firebird column definitions. */
CREATE TABLE upsert_test (
	username VARCHAR(100)  NOT NULL,
	score    INTEGER       DEFAULT 0 NOT NULL,
	CONSTRAINT pk_upsert_test PRIMARY KEY (username)
);

COMMIT;
