<?php
/**
 * Auto generated by prado-cli.php on 2007-04-05 10:25:19.
 */
class PostRecord extends TActiveRecord
{
	const TABLE='posts';

	public $post_id;

	public $author;

	public $create_time;

	public $title;

	public $content;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>