<?php
/**
 * Auto generated by prado-cli.php on 2007-04-05 10:23:57.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='users';

	public $username;

	public $email;

	public $password;

	public $role;

	public $first_name;

	public $last_name;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>