#!/usr/bin/env php
<?php
/**
 * Prado command line script for Unix/Linux.
 *
 * This is the bootstrap script for running prado-cli on Unix/Linux.
 *
 * @author Wei Zhuo <weizhuo[at]gmail[dot]com>
 * @link http://www.pradosoft.com/
 * @copyright Copyright &copy; 2005-2008 PradoSoft
 * @version $Id$
 */

require_once(dirname(__FILE__).'/prado-cli.php');
